Fixed Issue 458. (errors observing lecturebot/gamesbot). Fixed Issue 344.
There is still an issue when updating the TextAreaMoveList at times when there are no moves in the game. I have yet to fix this one.:

2011-03-01 21:22:18,573 ERROR IcsConnector:40 - Error in exceute
java.lang.IllegalArgumentException: Index out of bounds
        at org.eclipse.swt.SWT.error(Unknown Source)
        at org.eclipse.swt.SWT.error(Unknown Source)
        at org.eclipse.swt.SWT.error(Unknown Source)
        at org.eclipse.swt.custom.StyledText.replaceTextRange(Unknown Source)
        at raptor.swt.chess.movelist.TextAreaMoveList.updateToGame(TextAreaMoveList.java:232)
        at raptor.swt.chess.controller.ObserveController.refresh(ObserveController.java:386)
        at raptor.swt.chess.ChessBoardController.refresh(ChessBoardController.java:559)
        at raptor.swt.chess.controller.ObserveController$1$4.execute(ObserveController.java:160)
        at raptor.util.RaptorRunnable.run(RaptorRunnable.java:51)
        at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
        at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
        at org.eclipse.jface.window.Window.open(Window.java:801)
        at raptor.Raptor.main(Raptor.java:182)
2011-03-01 21:22:24,592 ERROR IcsConnector:40 - Error in exceute
java.lang.IllegalArgumentException: Index out of bounds
        at org.eclipse.swt.SWT.error(Unknown Source)
        at org.eclipse.swt.SWT.error(Unknown Source)
        at org.eclipse.swt.SWT.error(Unknown Source)
        at org.eclipse.swt.custom.StyledText.replaceTextRange(Unknown Source)
        at raptor.swt.chess.movelist.TextAreaMoveList.updateToGame(TextAreaMoveList.java:232)
        at raptor.swt.chess.controller.ObserveController.refresh(ObserveController.java:386)
        at raptor.swt.chess.ChessBoardController.refresh(ChessBoardController.java:559)
        at raptor.swt.chess.controller.ObserveController$1$4.execute(ObserveController.java:160)
        at raptor.util.RaptorRunnable.run(RaptorRunnable.java:51)
        at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
        at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
        at org.eclipse.jface.window.Window.open(Window.java:801)
        at raptor.Raptor.main(Raptor.java:182)